name: Code checks

on:
  - push
  - pull_request

jobs:
  code-checks:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Check formatting
        run: |
          cat data.json | python -m json.tool --indent 2 > formatted.json
          if ! diff formatted.json data.json &>/dev/null; then
            echo "Wrongly formatted data.json dude"
            exit 1
          fi
