name: Code checks

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.event.number || github.sha }}
  cancel-in-progress: true

jobs:
  code-checks:
    timeout-minutes: 10
    runs-on: [ubuntu-latest]

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - uses: pnpm/action-setup@v2
        with:
          version: 6.0.2

      - uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Install deps
        run: pnpm install

      - name: CI
        run: pnpm ci
